import { expect, test } from "vitest";

import { parseYarnLockfile } from "./yarn.ts";

test("parseYarnLockfile counts resolution blocks in a classic v1 lockfile", () => {
  // One block per resolved version; comma-joined ranges share a block.
  const summary = parseYarnLockfile(
    [
      "# yarn lockfile v1",
      "",
      "",
      '"@babel/code-frame@^7.0.0":',
      '  version "7.12.11"',
      '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/x.tgz"',
      "  dependencies:",
      '    "@babel/highlight" "^7.10.4"',
      "",
      "lodash@^4.17.0, lodash@^4.17.21:",
      '  version "4.17.21"',
      '  resolved "https://registry.yarnpkg.com/lodash/-/lodash.tgz"',
      "",
      "chalk@^2.0.0:",
      '  version "2.4.2"',
      "",
    ].join("\n"),
  );

  expect(summary).toStrictEqual({
    packageManager: "yarn",
    lockfileVersion: "1",
    resolvedCount: 3,
  });
});

test("parseYarnLockfile reads Berry YAML, excluding metadata and workspaces", () => {
  const summary = parseYarnLockfile(
    [
      "# This file is generated by running yarn install.",
      "",
      "__metadata:",
      "  version: 6",
      "  cacheKey: 8",
      "",
      '"@babel/code-frame@npm:^7.0.0":',
      "  version: 7.12.11",
      '  resolution: "@babel/code-frame@npm:7.12.11"',
      "",
      '"lodash@npm:^4.17.0, lodash@npm:^4.17.21":',
      "  version: 4.17.21",
      '  resolution: "lodash@npm:4.17.21"',
      "",
      '"root@workspace:.":',
      "  version: 0.0.0-use.local",
      '  resolution: "root@workspace:."',
      "",
    ].join("\n"),
  );

  expect(summary).toStrictEqual({
    packageManager: "yarn",
    lockfileVersion: "6",
    resolvedCount: 2,
  });
});
